// Подставной мост для скриншотов: интерфейс настоящий, а ядра нет — данные приходят из scripts/screenshots.js.
const { contextBridge, ipcRenderer } = require('electron');

const data = ipcRenderer.sendSync('demo:data');
const handlers = {};
const on = (name) => (cb) => (handlers[name] = cb);
const none = async () => null;

contextBridge.exposeInMainWorld('jarvis', {
  ask: () => new Promise(() => {}),
  onSayPart: on('sayPart'),
  onFiller: on('filler'),
  openLink: none,
  settings: async () => data.settings,
  settingsGet: async () => data.settingsGet,
  settingsSave: async () => ({ ok: true }),
  restart: () => {},
  replyConfirm: () => {},
  reset: () => {},
  cancel: () => {},
  dialogEnd: () => {},
  presence: () => {},
  minimize: () => {},
  pin: () => {},
  orbHeight: () => {},
  onConfirm: on('confirm'),
  onQuestion: on('question'),
  replyQuestion: () => {},
  onEnrollOffer: on('enrollOffer'),
  onStatus: on('status'),
  onFocus: on('focus'),
  onMode: on('mode'),
  onSetup: (cb) => (on('setup')(cb), () => {}),
  onSetupOffer: on('setupOffer'),
  setupAnswer: () => {},
  onBrainOffer: on('brainOffer'),
  brainAnswer: () => {},
  openSettings: () => {},
  onSettingsPage: on('settingsPage'),
  previewVoice: () => {},
  onPreviewVoice: on('previewVoice'),
  onSettingsChanged: on('settingsChanged'),
  components: async () => data.components,
  installComponent: async () => ({ ok: true }),
  mcpList: async () => data.mcp,
  mcpInstall: async () => ({ ok: true, ...data.mcp }),
  mcpAdd: async () => ({ ok: true, ...data.mcp }),
  mcpRemove: async () => ({ ok: true, ...data.mcp }),
  mcpTrust: async () => ({ ok: true, ...data.mcp }),
  mcpImport: async () => ({ ok: true, ...data.mcp }),
  mcpEnable: async () => ({ ok: true, ...data.mcp }),
  mcpTool: async () => ({ ok: true, ...data.mcp }),
  mcpCheck: async () => ({ ok: true, ...data.mcp }),
  mcpUpdate: async () => ({ ok: true, ...data.mcp }),
  onMcpChanged: () => () => {},
  modelsList: async () => data.models,
  updatesList: async () => data.updates,
  onUpdatesChanged: () => () => {},
  updatesCheck: async () => ({ ok: true, ...data.updates }),
  updatesApply: async () => ({ ok: true, ...data.updates }),
  updatesRollback: async () => ({ ok: true, ...data.updates }),
  onModelsChanged: () => () => {},
  modelsDownload: async () => ({ ok: true, ...data.models }),
  modelsUse: async () => ({ ok: true, ...data.models }),
  modelsRemove: async () => ({ ok: true, ...data.models }),
  modelsCancel: async () => ({ ok: true, ...data.models }),
  modelsLink: async () => ({ ok: true, ...data.models }),
  modelsImport: async () => ({ ok: true, ...data.models }),
  engineCheck: async () => ({ ok: true, ...data.models }),
  engineUpdate: async () => ({ ok: true, ...data.models }),
  engineRollback: async () => ({ ok: true, ...data.models }),
  onUpdate: on('update'),
  updateCheck: none,
  sendAudio: () => {},
  micReset: () => {},
  setListening: () => {},
  synth: none,
  onRemind: on('remind'),
  onRadio: on('radio'),
  onAlarm: on('alarm'),
  alarmSnooze: () => {},
  radioState: () => {},
  onAnnounce: on('announce'),
  onSessionEnd: on('sessionEnd'),
  onToggleMic: on('toggleMic'),
  onHeard: on('heard'),
  people: async () => data.settings.speaker,
  enrollStart: async () => ({ needed: 4 }),
  enrollAdd: none,
  enrollCancel: none,
  enrollFinish: none,
  personUpdate: none,
  personRemove: none,
  wakeLearn: none,
});

// Сцены вызывают события окна так же, как их вызвало бы ядро
contextBridge.exposeInMainWorld('demo', { emit: (name, payload) => handlers[name]?.(payload) });
